# 定义在这里 Deps.Version.xxxx 就能直接使用
# 只有一个地方使用的 version 不要写在这里，直接写版本号
# 命令方式不要带上 Version ，直接写名字，比如 okhttp 写 okhttp，不要写 okhttpVersion

androidxDesignVersion: "1.0.0-rc01"
androidxSupportVersion: "1.1.0"
rxjava2Version: "2.2.14"
rxandroid2Version: "2.1.1"
okhttpVersion: "3.12.1"
okioVersion: "1.9.0"
gsonVersion: "2.2.4"
svgaVersion: "2.5.9.25"
tinkerVersion: "1.9.14.17.2"
buglyVersion: "3.4.4"
buglyNdkVersion: "3.9.2"
realmVersion: "10.7.1"
butterknifeVersion: "10.0.0"
ccplayerVersion: "1.5.6.200"
ccliveengineVersion: "2.0.0.008"
ccavpVersion: "1.1.9"
annotationApiVersion: "1.3.1"
ccliveSdkVersion: "1.4.8.101"
coverQualityVersion: "1.2.0.202"
constraintlayout_version: "2.1.3"
leakCanaryVersion: "2.7"
ueToolVersion: "1.3.4.2"
DAGGER_VERSION: "2.38.1"
DAGGER_HILT_VERSION: "2.38.1"
ccMappingFileVersion: "0.0.6"
flutterAarVersion: "1.0.107-master"
koomVersion: "2.0.1"
ccgadgetVersion: "0.2.4.5"
mmkvVersion: "1.2.13"
ccminiVersion: "2.2.0.418424b9.cc"
ccCoverageVersion: "1.2.9"
ccLogVersion: "1.1.1"
qigsawVersion: "1.5.6.2"
autoDisposeVersion: "0.0.6"
multitypeVersion: "4.3.0"
baseadapterRecyclerviewVersion: "1.0.0"
