name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: active gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
        #      - run: curl -X POST ${{ secrets.WeChart_Push_URL }} -H 'content-type:application/json' -d '{ "channelName":"GitHubPlanAssistant","text":"Android程序已成功打包并提交fir.im！" }'
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app.apk
          path: host/build/outputs/apk/debug/host-debug.apk


